name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y make shellcheck bats
      - name: Ensure exec bits
        run: |
          chmod +x install.sh || true
          chmod +x scripts/menu.sh || true
          chmod +x scripts/bin/sys_info.sh || true
          chmod +x scripts/shell_select.sh 2>/dev/null || true
      - name: Lint
        run: make lint
      - name: Test
        run: make test

  windows-msys2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            make
            bats
      - name: Ensure exec bits
        shell: msys2 {0}
        run: |
          chmod +x install.sh || true
          chmod +x scripts/menu.sh || true
          chmod +x scripts/bin/sys_info.sh || true
          chmod +x scripts/shell_select.sh 2>/dev/null || true
      # Pas de lint côté Windows (shellcheck absent) : on exécute seulement les tests
      - name: Test (MSYS2)
        shell: msys2 {0}
        run: make test
