name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write   # ⬅️ nécessaire pour créer la release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ⬅️ récupère les tags pour git describe si besoin

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Set VERSION from tag
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Ensure exec bits & LF
        run: |
          chmod +x install.sh || true
          chmod +x scripts/menu.sh || true
          chmod +x scripts/bin/sys_info.sh || true
          chmod +x scripts/shell_select.sh 2>/dev/null || true
          # afficher le shebang et détecter CRLF si jamais
          head -n1 install.sh || true
          if file install.sh | grep -qi crlf; then
            echo "CRLF detected in install.sh"; exit 1; fi

      - name: Build package
        run: make package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
          generate_release_notes: true

      - name: Upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/menu-shells-${{ env.VERSION }}.tar.gz
